# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e171a2638d26cc4583b476f5e77fa48b805c86b6cc7f02e0275582113481adbed4ce7e23fde9501fb90d963f3f3840db4834a39f125d977f05438e0f4f9bc8e

test:
  secret_key_base: 47418de64d5a69bfc7ea2af470cfe2bf7a6a4f38b8f67222a461806b1720cbd75680d7b7ba6f8c683391227b60c2dfd09a6978e00a3a1a28c0730a06f25e8dfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
